canonical: https://gematik.de/fhir/erpchrg
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false

version: "1.0.4"
dependencies:
  hl7.fhir.r4.core: 4.0.1
  de.basisprofil.r4: 1.5.0
  de.gematik.erezept-workflow.r4: 1.4.x
  kbv.ita.for: 1.1.0