id: fhir-profiles-erpchrg
canonical: https://gematik.de/fhir/erpchrg
name: Abrechnungsinformationen des E-Rezeptes für den Patienten
title: ePrescription patient receipt definition
description: German fhir profiles on ePrescription patient receipt
fhirVersion: 4.0.1
applyExtensionMetadataToRoot: false
status: draft
version: "1.0"
copyrightYear: 2022+
releaseLabel: draft
publisher:
  name: Gematik GmbH
  url: https://www.gematik.de/
  email: info@gematik.de
dependencies:
  de.basisprofil.r4: 1.3.2
  hl7.fhir.r4.core: 4.0.1
  de.gematik.erezept-workflow.r4: 1.2.0
  kbv.ita.for: 1.1.0
  kbv.basis: 1.3.0
  de.abda.eRezeptAbgabedatenPKV: 1.1.0-rc12
