canonical: https://gematik.de/fhir/erpchrg
fhirVersion: 4.0.1
FSHOnly: true
applyExtensionMetadataToRoot: false

version: "1.0.3"
dependencies:
  de.basisprofil.r4: 1.3.2
  hl7.fhir.r4.core: 4.0.1
  de.gematik.erezept-workflow.r4: 1.3.x
  kbv.ita.for: 1.1.0
  kbv.ita.erp: 1.1.x
  de.abda.erezeptabgabedatenpkv: 1.2.0