Instance: 4d8684f1-e379-4cb2-adcb-41ab1a543206
InstanceOf: Bundle
Usage: #example
* meta.lastUpdated = "2022-06-14T13:54:15.203+00:00"
* type = #searchset
* total = 2
* link.relation = "self"
* link.url = "https://prescriptionserver.telematik/ChargeItem/abc825bc-bc30-45f8-b109-1b343fff5c45?ac=777bea0e13cc9c42ceec14aec3ddee2263325dc2c6c699db115f58fe423607ea"
* entry[0].fullUrl = "https://prescriptionserver.telematik/ChargeItem/abc825bc-bc30-45f8-b109-1b343fff5c45"
* entry[=].resource = ChargeItemExampleBundles
* entry[=].search.mode = #match
* entry[+].fullUrl = "https://prescriptionserver.telematik/Bundle/a5142020-7b59-4674-9b02-08f68c583610"
* entry[=].resource = a5142020-7b59-4674-9b02-08f68c583610
* entry[=].search.mode = #include


Instance: a5142020-7b59-4674-9b02-08f68c583610
InstanceOf: Bundle
Usage: #inline
* meta.profile = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-PKV-PR-ERP-AbgabedatenBundle|1.1"
* meta.tag[0].display = "Beispiel RezeptAbgabedatenPKV Bundle (FAM + Noctu + Rezeptänderung)"
* meta.tag[+].display = "ACHTUNG! Der fachlich korrekte Inhalt der Beispielinstanz kann nicht gewährleistet werden. Wir sind jederzeit dankbar für Hinweise auf Fehler oder für Verbesserungsvorschläge."
* identifier.system = "https://gematik.de/fhir/erp/NamingSystem/GEM_ERP_NS_PrescriptionId"
* identifier.value = "200.100.000.000.082.87"
* type = #document
* timestamp = "2022-03-25T23:40:00Z"
* entry[0].fullUrl = "urn:uuid:4dc5f425-b9b6-4e39-9166-42668ead6c86"
* entry[=].resource.resourceType = "Composition"
* entry[=].resource.id = "4dc5f425-b9b6-4e39-9166-42668ead6c86"
* entry[=].resource.meta.profile = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-PKV-PR-ERP-AbgabedatenComposition|1.1"
* entry[=].resource.status = #final
* entry[=].resource.type = http://fhir.abda.de/eRezeptAbgabedaten/CodeSystem/DAV-CS-ERP-CompositionTypes#ERezeptAbgabedaten
* entry[=].resource.date = "2022-03-25T23:40:00Z"
* entry[=].resource.author.reference = "urn:uuid:1fa57d53-812b-4cab-a42e-94a12481108a"
* entry[=].resource.title = "ERezeptAbgabedaten"
* entry[=].resource.section[0].title = "Abgabeinformationen"
* entry[=].resource.section[=].entry.reference = "urn:uuid:37a647b8-cb89-491a-af0f-f9bffc2b386c"
* entry[=].resource.section[+].title = "Apotheke"
* entry[=].resource.section[=].entry.reference = "urn:uuid:1fa57d53-812b-4cab-a42e-94a12481108a"
* entry[+].fullUrl = "urn:uuid:1fa57d53-812b-4cab-a42e-94a12481108a"
* entry[=].resource.resourceType = "Organization"
* entry[=].resource.id = "1fa57d53-812b-4cab-a42e-94a12481108a"
* entry[=].resource.meta.profile = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-PKV-PR-ERP-Apotheke|1.1"
* entry[=].resource.identifier.system = "http://fhir.de/sid/arge-ik/iknr"
* entry[=].resource.identifier.value = "123456789"
* entry[=].resource.name = "Adler-Apotheke"
* entry[=].resource.address.type = #physical
* entry[=].resource.address.line = "Taunusstraße 89"
* entry[=].resource.address.line.extension[0].url = "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetName"
* entry[=].resource.address.line.extension[=].valueString = "Taunusstraße"
* entry[=].resource.address.line.extension[+].url = "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber"
* entry[=].resource.address.line.extension[=].valueString = "89"
* entry[=].resource.address.city = "Langen"
* entry[=].resource.address.postalCode = "63225"
* entry[=].resource.address.country = "D"
* entry[+].fullUrl = "urn:uuid:37a647b8-cb89-491a-af0f-f9bffc2b386c"
* entry[=].resource.resourceType = "MedicationDispense"
* entry[=].resource.id = "37a647b8-cb89-491a-af0f-f9bffc2b386c"
* entry[=].resource.meta.profile = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-PKV-PR-ERP-Abgabeinformationen|1.1"
* entry[=].resource.extension[0].url = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-Abrechnungszeilen"
* entry[=].resource.extension[=].valueReference.reference = "urn:uuid:8a99bfa5-f7aa-4741-99d8-f1abbd301ae1"
* entry[=].resource.extension[+].url = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-PKV-EX-ERP-AbrechnungsTyp"
* entry[=].resource.extension[=].valueCodeableConcept = http://fhir.abda.de/eRezeptAbgabedaten/CodeSystem/DAV-PKV-CS-ERP-AbrechnungsTyp#1
* entry[=].resource.status = #completed
* entry[=].resource.medicationCodeableConcept = http://terminology.hl7.org/CodeSystem/data-absent-reason#not-applicable
* entry[=].resource.performer.actor.reference = "urn:uuid:1fa57d53-812b-4cab-a42e-94a12481108a"
* entry[=].resource.authorizingPrescription.identifier.system = "https://gematik.de/fhir/erp/NamingSystem/GEM_ERP_NS_PrescriptionId"
* entry[=].resource.authorizingPrescription.identifier.value = "200.100.000.000.082.87"
* entry[=].resource.type = http://fhir.abda.de/eRezeptAbgabedaten/CodeSystem/DAV-CS-ERP-MedicationDispenseTyp#Abgabeinformationen
* entry[=].resource.whenHandedOver = "2022-03-25"
* entry[=].resource.substitution.extension.url = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-Rezeptaenderung"
* entry[=].resource.substitution.extension.extension[0].url = "ArtRezeptaenderung"
* entry[=].resource.substitution.extension.extension[=].valueCodeableConcept = http://fhir.abda.de/eRezeptAbgabedaten/CodeSystem/DAV-PKV-CS-ERP-ArtRezeptaenderung#21
* entry[=].resource.substitution.extension.extension[+].url = "RueckspracheArzt"
* entry[=].resource.substitution.extension.extension[=].valueCodeableConcept = http://fhir.abda.de/eRezeptAbgabedaten/CodeSystem/DAV-CS-ERP-RueckspracheArzt#2
* entry[=].resource.substitution.wasSubstituted = true
* entry[+].fullUrl = "urn:uuid:8a99bfa5-f7aa-4741-99d8-f1abbd301ae1"
* entry[=].resource.resourceType = "Invoice"
* entry[=].resource.id = "8a99bfa5-f7aa-4741-99d8-f1abbd301ae1"
* entry[=].resource.meta.profile = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-PKV-PR-ERP-Abrechnungszeilen|1.1"
* entry[=].resource.status = #issued
* entry[=].resource.type = http://fhir.abda.de/eRezeptAbgabedaten/CodeSystem/DAV-CS-ERP-InvoiceTyp#Abrechnungszeilen
* entry[=].resource.lineItem[0].sequence = 1
* entry[=].resource.lineItem[=].chargeItemCodeableConcept = http://fhir.de/CodeSystem/ifa/pzn#11514676
* entry[=].resource.lineItem[=].priceComponent.extension[0].url = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-MwStSatz"
* entry[=].resource.lineItem[=].priceComponent.extension[=].valueDecimal = 19
* entry[=].resource.lineItem[=].priceComponent.extension[+].url = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-KostenVersicherter"
* entry[=].resource.lineItem[=].priceComponent.extension[=].extension[0].url = "Kategorie"
* entry[=].resource.lineItem[=].priceComponent.extension[=].extension[=].valueCodeableConcept = http://fhir.abda.de/eRezeptAbgabedaten/CodeSystem/DAV-PKV-CS-ERP-KostenVersicherterKategorie#0
* entry[=].resource.lineItem[=].priceComponent.extension[=].extension[+].url = "Kostenbetrag"
* entry[=].resource.lineItem[=].priceComponent.extension[=].extension[=].valueMoney.value = 0
* entry[=].resource.lineItem[=].priceComponent.extension[=].extension[=].valueMoney.currency = #EUR
* entry[=].resource.lineItem[=].priceComponent.type = #informational
* entry[=].resource.lineItem[=].priceComponent.factor = 2
* entry[=].resource.lineItem[=].priceComponent.amount.value = 48.98
* entry[=].resource.lineItem[=].priceComponent.amount.currency = #EUR
* entry[=].resource.lineItem[+].extension.url = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-Zusatzattribute"
* entry[=].resource.lineItem[=].extension.extension.url = "ZusatzattributAbgabeNoctu"
* entry[=].resource.lineItem[=].extension.extension.extension[0].url = "Gruppe"
* entry[=].resource.lineItem[=].extension.extension.extension[=].valueCodeableConcept = http://fhir.abda.de/eRezeptAbgabedaten/CodeSystem/DAV-CS-ERP-ZusatzattributGruppe#11
* entry[=].resource.lineItem[=].extension.extension.extension[+].url = "DatumUhrzeit"
* entry[=].resource.lineItem[=].extension.extension.extension[=].valueDateTime = "2022-03-25T23:30:00.0Z"
* entry[=].resource.lineItem[=].extension.extension.extension[+].url = "Schluessel"
* entry[=].resource.lineItem[=].extension.extension.extension[=].valueBoolean = true
* entry[=].resource.lineItem[=].sequence = 2
* entry[=].resource.lineItem[=].chargeItemCodeableConcept = http://fhir.de/CodeSystem/ifa/pzn#02567018
* entry[=].resource.lineItem[=].priceComponent.extension[0].url = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-MwStSatz"
* entry[=].resource.lineItem[=].priceComponent.extension[=].valueDecimal = 19
* entry[=].resource.lineItem[=].priceComponent.extension[+].url = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-KostenVersicherter"
* entry[=].resource.lineItem[=].priceComponent.extension[=].extension[0].url = "Kategorie"
* entry[=].resource.lineItem[=].priceComponent.extension[=].extension[=].valueCodeableConcept = http://fhir.abda.de/eRezeptAbgabedaten/CodeSystem/DAV-PKV-CS-ERP-KostenVersicherterKategorie#0
* entry[=].resource.lineItem[=].priceComponent.extension[=].extension[+].url = "Kostenbetrag"
* entry[=].resource.lineItem[=].priceComponent.extension[=].extension[=].valueMoney.value = 0
* entry[=].resource.lineItem[=].priceComponent.extension[=].extension[=].valueMoney.currency = #EUR
* entry[=].resource.lineItem[=].priceComponent.type = #informational
* entry[=].resource.lineItem[=].priceComponent.factor = 1
* entry[=].resource.lineItem[=].priceComponent.amount.value = 2.5
* entry[=].resource.lineItem[=].priceComponent.amount.currency = #EUR
* entry[=].resource.totalGross.extension.url = "http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-Gesamtzuzahlung"
* entry[=].resource.totalGross.extension.valueMoney.value = 0
* entry[=].resource.totalGross.extension.valueMoney.currency = #EUR
* entry[=].resource.totalGross.value = 51.48
* entry[=].resource.totalGross.currency = #EUR